### ISSUE TITLE
foxit阅读器编辑PDF下，无法自动删除换行

### ISSUE THREAD

**Issue by zzzbbs** [yuhldr/ldr-translate#10]
0. 系统版本
    ubuntu 21.04

1. 软件版本
    1.5.1
 

2. 做什么发生的这个问题，是否可以重复出现此问题？
    [在福昕阅读器软件中复制文献中的摘要出现。]附件中为翻译结果及对应文献

![2022-09-05 09-01-57 的屏幕截图](https://user-images.githubusercontent.com/81844650/188341613-f1b32d33-f0ab-4f08-b210-82ce36d70db0.png)

[2106.09422.pdf](https://github.com/yuhldr/ldr-translate/files/9485872/2106.09422.pdf)

**Comment by yuhldr** [comment]
已修复，看[1.5.2预览版](https://github.com/yuhldr/ldr-translate/releases/tag/v1.5.2)
