### ISSUE TITLE
对PDF进行换行时，如果换行位置有“-”符，也会影响删除换行效果

### ISSUE THREAD

**Issue by zzzbbs** [yuhldr/ldr-translate#11]
0. 系统版本
    ubuntu 21.04

1. 软件版本
    1.5.2
 

2. 做什么发生的这个问题，是否可以重复出现此问题？
    在用翻译器时，似乎pdf换行位置有“-”连接符，翻译结果就会换行，可见附件图的效果，对窗口进行拖动，识别出的仍会自动换行。
![2022-09-05 17-23-36 的屏幕截图](https://user-images.githubusercontent.com/81844650/188416546-a1913a9a-599e-40ff-bf38-80563bb5e88f.png)
![2022-09-05 17-27-31 的屏幕截图](https://user-images.githubusercontent.com/81844650/188416686-18b14e1b-956d-489c-b39a-8bda7d1e43e0.png)

**Comment by zzzbbs** [comment]
软件整体使用效果较linux下其他软件优秀好多，像crow_translate，golden dict我都试过，都不好用，给周围朋友力推！！！

**Comment by zzzbbs** [comment]
discrim- nate那行 第二张图 没有换行，是因为我自己处理了一下，把换行去掉了，看看会不会影响翻译效果。

**Comment by yuhldr** [comment]
感谢支持，但是这个问题我没复现出来，你把这个pdf文件上传我测试看看
![image](https://user-images.githubusercontent.com/25719023/188471492-17362422-04c9-45b7-9e31-cac8b2ef95ff.png)

**Comment by zzzbbs** [comment]
[Shen 等。 - 2022 - Learning Category-Level Generalizable Object Manip.pdf](https://github.com/yuhldr/ldr-translate/files/9490569/Shen.-.2022.-.Learning.Category-Level.Generalizable.Object.Manip.pdf)

**Comment by zzzbbs** [comment]
不知是否是我的PDF阅读器的问题，如果调试没问题，我明天换一个PDF阅读器测试一下

**Comment by yuhldr** [comment]
> 不知是否是我的PDF阅读器的问题，如果调试没问题，我明天换一个PDF阅读器测试一下

应该是的，不过大概问题可能是这个阅读器导致 - 以后的下一行，有个空格，我改一下试试

**Comment by yuhldr** [comment]
已修复 [1.5.3](https://github.com/yuhldr/ldr-translate/releases/tag/v1.5.3)
