### ISSUE TITLE
追加模式下复制一次，翻译里追加了两次

### ISSUE THREAD

**Issue by zzzbbs** [yuhldr/ldr-translate#12]
0. 系统版本
    ubuntu 21.04

1. 软件版本
    1.5.3
 

2. 做什么发生的这个问题，是否可以重复出现此问题？
出现问题的视频在如下压缩包中
    
[translate_bug.zip](https://github.com/yuhldr/ldr-translate/files/9493965/translate_bug.zip)

**Comment by yuhldr** [comment]
收到，这几天有些事，过几天修改一下，暂时可以换个pdf阅读器
