### ISSUE TITLE
翻译遇到‘#’号，就会停止，用网页上的谷歌不会

### ISSUE THREAD

**Issue by zzzbbs** [yuhldr/ldr-translate#13]
0. 系统版本
    ubuntu21.04

1. 软件版本
    1.5.3
 

2. 做什么发生的这个问题，是否可以重复出现此问题？
    > 如，在 `okular` 软件中复制 `文献` 中的 `哪句话` 出现，建议上传文献附件以及对应截图
![屏幕截图 2022-09-13 16:42:58](https://user-images.githubusercontent.com/81844650/190035166-3c5c174d-c14e-412e-87f1-d2c4c5eddb26.png)
![屏幕截图 2022-09-14 09:00:30](https://user-images.githubusercontent.com/81844650/190035313-691b1453-988e-49d2-83be-de6209950f78.png)

**Comment by zzzbbs** [comment]
翻译原文：
Most surprising finding #1: regularizers. While many of our findings confirm common practices in AIL research, some of them are surprising or even contradict prior work. In particular, we find that standard regularizers from Supervised Learning — dropout [10] and weight decay [1] often perform similarly to the regularizers designed specifically for adversarial learning like gradient penalty [18].
 Moreover, for easier environments (which were often the only ones used in prior work), we find that it is possible to achieve excellent results without using any explicit discriminator regularization.

**Comment by yuhldr** [comment]
- #12 
- #13

这两个问题都解决了，安装试一下 

```bash
unzip ldr.zip && sudo dpkg -i ldr-translate.deb
``` 

[ldr.zip](https://github.com/yuhldr/ldr-translate/files/9565929/ldr.zip)

**Comment by zzzbbs** [comment]
感谢～ 我测试了一下 #13 解决了， #12取消追加模式，再复制好像有些问题，没有办法正常显示原文，复制后还是原来追加的原文，这部分问题我明天录个视频给你看下～

**Comment by zzzbbs** [comment]
> * [追加模式下复制一次，翻译里追加了两次 #12](https://github.com/yuhldr/ldr-translate/issues/12)
> 
>     * [翻译遇到‘#’号，就会停止，用网页上的谷歌不会 #13](https://github.com/yuhldr/ldr-translate/issues/13)
> 
> 
> 这两个问题都解决了，安装试一下
> 
> ```shell
> unzip ldr.zip && sudo dpkg -i ldr-translate.deb
> ```
> 
> [ldr.zip](https://github.com/yuhldr/ldr-translate/files/9565929/ldr.zip)

感谢～ 我测试了一下 https://github.com/yuhldr/ldr-translate/issues/13 解决了， #12取消追加模式，再复制好像有些问题，没有办法正常显示原文，复制后还是原来追加的原文，这部分问题我明天录个视频给你看下～

**Comment by zzzbbs** [comment]
> * [追加模式下复制一次，翻译里追加了两次 #12](https://github.com/yuhldr/ldr-translate/issues/12)
> 
>     * [翻译遇到‘#’号，就会停止，用网页上的谷歌不会 #13](https://github.com/yuhldr/ldr-translate/issues/13)
> 
> 
> 这两个问题都解决了，安装试一下
> 
> ```shell
> unzip ldr.zip && sudo dpkg -i ldr-translate.deb
> ```
> 
> [ldr.zip](https://github.com/yuhldr/ldr-translate/files/9565929/ldr.zip)
你好，我这台新电脑测试了没有问题。昨天那台电脑测试了有问题，可能是有软件包冲突了。
