### ISSUE TITLE
你好 这个工具最近几天在我的电脑上抽风。报错Main,py无响应，运行谷歌翻译是不是需要挂代理。

### ISSUE THREAD

**Issue by eillenlun** [yuhldr/ldr-translate#14]
0. 系统版本
    > ubuntu20.04

1. 软件版本
    > 1.5.0和1.5.3
 
![image](https://user-images.githubusercontent.com/42166064/192677140-b5feb06b-d532-452a-8b7d-7e97307941c9.png)

2.相较于百度api 则不会报错，但是百度api显示账号错误，修改密码更换api也是无效的。难顶

3. 这个对我电脑的python版本有要求么？最近也没做什么操作，电脑可以正常科学上网。

**Comment by yuhldr** [comment]
谷歌翻译最近好像国内没法用了

百度翻译应该没问题，你先彻底退出兰译，
然后输入如下，把配置删一下
```bash
rm -rf ~/.config/ldr-translate
```
然后打开兰译，并且设置百度的api和秘钥重新设置一下

**Comment by eillenlun** [comment]
好的  感谢！！

**Comment by phyzhenli** [comment]
最近谷歌翻出了问题，golden dict坏掉了，找了一下找到了这里，申请了百度api，非常方便！感谢贡献！
