### ISSUE TITLE
软件打不开

### ISSUE THREAD

**Issue by CapenZen** [yuhldr/ldr-translate#16]
您好，我安装完软件后点击图标打不开软件，请问是什么原因？

**Comment by CapenZen** [comment]
想问一下能不能通过命令行打开这个软件呢？我是用deb安装的

**Comment by yuhldr** [comment]
终端输入ldr，可以打开，如果有报错，发一下我看看

或者你参考 [这里](https://gitee.com/yuhldr/ldr-translate/issues/I5KSRE) 处理看看

**Comment by CapenZen** [comment]
> 

capen@lucky:~/下载$ ldr
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by yuhldr** [comment]
[参考这里](https://gitee.com/yuhldr/ldr-translate/issues/I5KSRE)

**Comment by CapenZen** [comment]
> [参考这里](https://gitee.com/yuhldr/ldr-translate/issues/I5KSRE)

capen@lucky:~/桌面$ pip3 install gobject
Requirement already satisfied: gobject in /home/capen/.local/lib/python3.8/site-packages (0.1.0)
capen@lucky:~/桌面$ ldr
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
capen@lucky:~/桌面$ 
好像还是不行

**Comment by CapenZen** [comment]
我Uubuntu20.04版本的

**Comment by yuhldr** [comment]
不同系统不一样，你看上面连接里我最后[那个回复](https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-getting-started)

ubuntu正常系统应该有的，你应该是哪里改错了

输入这个试一下

```bash
sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0
```

**Comment by CapenZen** [comment]
capen@lucky:~/桌面$ sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0
[sudo] capen 的密码： 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python3-gi 已经是最新版 (3.36.0-1)。
python3-gi-cairo 已经是最新版 (3.36.0-1)。
gir1.2-gtk-3.0 已经是最新版 (3.24.20-0ubuntu1.1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 102 个软件包未被升级。
capen@lucky:~/桌面$ ldr
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

这个包我也安装过了，也不行鸭

**Comment by yuhldr** [comment]
算了，你安装qt版本那个吧，qt结尾那个deb包

先卸载之前的

```bash
sudo apt remove ldr-translate
```

**Comment by CapenZen** [comment]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from PyQt5.QtGui import QIcon
ModuleNotFoundError: No module named 'PyQt5'
他这个又有报错了

**Comment by yuhldr** [comment]
试试
```bash
sudo apt install python3-pyqt5
````

如果还是相同的报错，你重装系统吧，系统有问题

**Comment by CapenZen** [comment]
还是不行呀，我今天下午才重装的系统，应该没问题的...不过还是感谢作者耐心回答。

**Comment by yuhldr** [comment]
试试 [最新预览版](https://github.com/yuhldr/ldr-translate/releases/tag/%E8%87%AA%E5%8A%A8%E6%89%93%E5%8C%85)
