### ISSUE TITLE
你好，我总是添加不上API key，伴随着信息：超时或密码错误,百度腾讯都是如此

### ISSUE THREAD

**Issue by ZHAODONG-LYU** [yuhldr/ldr-translate#19]
0. 系统版本
    > 如 archlinux 2022.06.10滚动版、ubuntu22.04
ubuntu 2204

1. 软件版本
    > 如1.4.0
 v 1.6.0

2. 做什么发生的这个问题，是否可以重复出现此问题？
    > 如，在 `okular` 软件中复制 `文献` 中的 `哪句话` 出现，建议上传文献附件以及对应截图
![2022-11-09_01-52](https://user-images.githubusercontent.com/103206736/200639699-b2f0b049-5a03-4380-b067-316e1c301789.png)

**Comment by yuhldr** [comment]
问题1，有没有用vpn？
问题2，状态栏里退出软件，然后终端输入 ldr，再设置api，错误时终端里的信息发一下

**Comment by ZHAODONG-LYU** [comment]
> 问题1，有没有用vpn？ 问题2，状态栏里退出软件，然后终端输入 ldr，再设置api，错误时终端里的信息发一下

有vpn,但是没有vpn的情况我也尝试过，同样的错误;终端里的错误信息是：
`52003 UNAUTHORIZED USER
`

**Comment by yuhldr** [comment]
密钥或者密码输入错了，你仔细看一下那个教程，哪个是密钥，哪个是密码

**Comment by ZHAODONG-LYU** [comment]
好的谢谢，百度API没有仔细看教程，没有开通权限。开通权限之后解决了
