### ISSUE TITLE
ubuntu 18.04 命令行打开后图标卡死在右上角，且卸载后不消失

### ISSUE THREAD

**Issue by fengzhongsu** [yuhldr/ldr-translate#2]
![image](https://user-images.githubusercontent.com/32994975/145667018-9b9ba690-c961-4429-a872-b15dfb88ed58.png)

**Comment by yuhldr** [comment]
点“翻译中”，选择“完全退出”即可，[v1.2.1](https://github.com/yuhldr/ldr-translate/releases/tag/v1.2.1)，已适配ubuntu18.04（虚拟机测试通过）

**Comment by fengzhongsu** [comment]
您好，我已受到您的来信

**Comment by fengzhongsu** [comment]
您好，我已受到您的来信
