### ISSUE TITLE
程序中断

### ISSUE THREAD

**Issue by CXT-666** [yuhldr/ldr-translate#20]
0. 系统版本
    > 如 archlinux 2022.06.10滚动版、ubuntu22.04
ubuntu22.04

1. 软件版本
    > 如1.4.0
 1.6.0 gtk

2. 做什么发生的这个问题，是否可以重复出现此问题？
    > 如，在 `okular` 软件中复制 `文献` 中的 `哪句话` 出现，建议上传文献附件以及对应截图

选择原文ctrl c 程序会中断，，需要再次启动程序，就可以成功翻译同样的句子了，但是这种现象会经常发生。
![ldr](https://user-images.githubusercontent.com/64955896/202367065-3c5cdd23-1296-436e-a16f-28efe75995c4.png)

**Comment by CXT-666** [comment]
![caddn](https://user-images.githubusercontent.com/64955896/202368150-cdb414a7-715d-4790-8ac2-e181d14be7c9.png)
![cuowu](https://user-images.githubusercontent.com/64955896/202368170-13dd615b-f375-45d3-82f3-60ab575e0050.png)
翻译这段文献时会报这种错，不过再次启动ldr后，还是可以翻译同一段

**Comment by yuhldr** [comment]
不要用谷歌翻译，谷歌最近跑了。试试其他两种翻译？

**Comment by MiuKaShi** [comment]
> 不要用谷歌翻译，谷歌最近跑了。试试其他两种翻译？

即使用了baidu的api一样会崩溃，而且很频繁

**Comment by yuhldr** [comment]
> > 不要用谷歌翻译，谷歌最近跑了。试试其他两种翻译？
> 
> 即使用了baidu的api一样会崩溃，而且很频繁

最近会发一版修复

**Comment by yuhldr** [comment]
试试 [最新预览版](https://github.com/yuhldr/ldr-translate/releases/tag/%E8%87%AA%E5%8A%A8%E6%89%93%E5%8C%85)
