### ISSUE TITLE
HTTPS请求错误

### ISSUE THREAD

**Issue by zzzbbs** [yuhldr/ldr-translate#21]
0. 系统版本
    >ubuntu20.04

1. 软件版本
    > 最新版本
 

2. 做什么发生的这个问题，是否可以重复出现此问题？
    >最近经常出现，且无法解决，网络均正常
请求错误
HTTPSConnectionPool(host='translate.googleapis.com', port=443): Max retries exceeded with url: /translate_a/single?client=gtx&dt=t&sl=auto&tl=zh&q=For%20rhythmic%20movements,%20like%20waving%20a%20hand,%20g%20should%20prevent%20the%20trajectory%20to%20diverge%20even%20if%20the%20rollout%20length%20is%20infinite. (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f755098b040>, 'Connection to translate.googleapis.com timed out. (connect timeout=3)'))

**Comment by zzzbbs** [comment]
试图打开这个出错的网站，结果是打不开的。最近有时候翻译不出来，会闪退。我把源码里改成用有道的api就可以了

**Comment by yuhldr** [comment]
谷歌翻译最近被墙了，如果平时翻墙可以设置一下代理
