### ISSUE TITLE
使用qt版本，Append取消后还是会有原来的内容，需要重复几次复制才会正常

### ISSUE THREAD

**Issue by zzzbbs** [yuhldr/ldr-translate#22]
0. 系统版本
    >ubuntu20.04

1. 软件版本
    > 最新版
 

2. 做什么发生的这个问题，是否可以重复出现此问题？
    > 

https://user-images.githubusercontent.com/81844650/209070811-ab9aa8ec-8fb5-4222-a674-e9e696c89c9f.mp4

**Comment by yuhldr** [comment]
试试 [最新预览版](https://github.com/yuhldr/ldr-translate/releases/tag/%E8%87%AA%E5%8A%A8%E6%89%93%E5%8C%85)
