### ISSUE TITLE
换行问题

### ISSUE THREAD

**Issue by JianYu777** [yuhldr/ldr-translate#5]
作者您好，我发现无论是复制还是截图时，对于pdf文件的换行翻译问题都没有得到解决，请问是我有什么地方操作失误吗？

**Comment by yuhldr** [comment]
> 作者您好，我发现无论是复制还是截图时，对于pdf文件的换行翻译问题都没有得到解决，请问是我有什么地方操作失误吗？

用的哪个版本，什么系统，系统版本是？我测试看看

**Comment by yuhldr** [comment]
如果你指的是翻译以后最后几行有时不显示，你可以试一下1.4.0，应该好了
