### ISSUE TITLE
Manjaro下不会自动识别系统截图图片上的文字

### ISSUE THREAD

**Issue by Moriarty1024** [yuhldr/ldr-translate#8]
0. 系统版本
    > Manjaro

1. 软件版本
    > 如1.5.0
 

2. 做什么发生的这个问题，是否可以重复出现此问题？
    > 任何场景下的截图均无法识别图片上的文字，用的百度接口。翻译功能正常。

**Comment by yuhldr** [comment]
已修复，感谢反馈

**Comment by Moriarty1024** [comment]
新版本工作正常！给力！
