### ISSUE TITLE
没有 1.5.1  的标签 AUR 安装 404

### ISSUE THREAD

**Issue by ilovesusu** [yuhldr/ldr-translate#9]
0. 系统版本
    > archlinux 最新

1. 软件版本
    > 如1.5.1
 

在aur安装时 提示 https://github.com/yuhldr/ldr-translate/archive/refs/tags/v1.5.1.tar.gz 404
发现是 没有打 1.5.1  的标签啊

**Comment by yuhldr** [comment]
已修复
